# Generated by Django 5.2.12 on 2026-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('niche', models.CharField(blank=True, max_length=100, verbose_name='Ниша')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок на странице кейса')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Главное изображение')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='cases/details/', verbose_name='Изображение внутри кейса')),
                ('stat_1_value', models.CharField(blank=True, max_length=50, verbose_name='Стат 1 значение')),
                ('stat_1_label', models.CharField(blank=True, max_length=150, verbose_name='Стат 1 подпись')),
                ('stat_2_value', models.CharField(blank=True, max_length=50, verbose_name='Стат 2 значение')),
                ('stat_2_label', models.CharField(blank=True, max_length=150, verbose_name='Стат 2 подпись')),
                ('stat_3_value', models.CharField(blank=True, max_length=50, verbose_name='Стат 3 значение')),
                ('stat_3_label', models.CharField(blank=True, max_length=150, verbose_name='Стат 3 подпись')),
                ('stat_4_value', models.CharField(blank=True, max_length=50, verbose_name='Стат 4 значение')),
                ('stat_4_label', models.CharField(blank=True, max_length=150, verbose_name='Стат 4 подпись')),
                ('task', models.TextField(blank=True, verbose_name='Задача проекта')),
                ('what_we_did', models.TextField(blank=True, verbose_name='Что сделали')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('quote', models.TextField(blank=True, verbose_name='Цитата')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Услуга')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Период')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
