# Generated by Django 5.2.12 on 2026-03-25 06:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('seo', 'SEO'), ('ppc', 'PPC'), ('smm', 'SMM'), ('development', 'Разработка')], max_length=20)),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Короткий опис')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Час читання (хв)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
