# Generated by Django 5.2.12 on 2026-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Корпоративная почта')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram (личный)')),
                ('telegram_channel', models.URLField(blank=True, null=True, verbose_name='Telegram канал')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('threads', models.URLField(blank=True, null=True, verbose_name='Threads')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
